// Code generated by Civic Transparency schema generator; DO NOT EDIT.
//
// Source-schema:   series.schema.json
// Schema-sha256:   acf1664027df36e92afba906343a652cc07c12ebeb333467bed522cfb179c3b0
// Spec-version:    0.2.1
//
// This file contains the canonical Go representation of the schema above.
// JSON struct tags match the schema field names. Enumerations are expressed
// as typed string constants. Numeric and range constraints can be checked
// with the validation helpers in validation.go.  Package-level documentation
// is in doc.go.

// types/examples_test.go
package types_test

import (
    "encoding/json"
    "fmt"
    "github.com/civic-interconnect/civic-transparency-go-types/types"
)

func ExampleProvenanceTag() {
    tag := types.ProvenanceTag{
        AcctAgeBucket:   types.AcctAge_1_6m,
        AcctType:        types.AcctTypePerson,
        AutomationFlag:  types.AutomationManual,
        PostKind:        types.PostKindOriginal,
        ClientFamily:    types.ClientWeb,
        MediaProvenance: types.MediaProvNone,
        DedupHash:       "deadbeef",
    }
    b, _ := json.Marshal(tag)
    fmt.Println(string(b))
    // Output: {"acct_age_bucket":"1-6m","acct_type":"person", ...}
}
