// Code generated by Civic Transparency schema generator; DO NOT EDIT.
//
// Source-schema:   series.schema.json
// Schema-sha256:   acf1664027df36e92afba906343a652cc07c12ebeb333467bed522cfb179c3b0
// Spec-version:    0.2.1
//
// This file contains the canonical Go representation of the schema above.
// JSON struct tags match the schema field names. Enumerations are expressed
// as typed string constants. Numeric and range constraints can be checked
// with the validation helpers in validation.go.  Package-level documentation
// is in doc.go.

package types

type AcctAge string

const (
	AcctAge_0_7d AcctAge = "0-7d"
	AcctAge_8_30d AcctAge = "8-30d"
	AcctAge_1_6m AcctAge = "1-6m"
	AcctAge_6_24m AcctAge = "6-24m"
	AcctAge_24mPlus AcctAge = "24m+"
)

type AcctType string

const (
	AcctTypePerson           AcctType = "person"
	AcctTypeOrg              AcctType = "org"
	AcctTypeMedia            AcctType = "media"
	AcctTypePublicOfficial   AcctType = "public_official"
	AcctTypeUnverified       AcctType = "unverified"
	AcctTypeDeclaredAutomation AcctType = "declared_automation"
)

type AutomationFlag string

const (
	AutomationManual    AutomationFlag = "manual"
	AutomationScheduled AutomationFlag = "scheduled"
	AutomationAPICLIENT AutomationFlag = "api_client"
	AutomationDeclaredBot AutomationFlag = "declared_bot"
)

type PostKind string

const (
	PostKindOriginal PostKind = "original"
	PostKindReshare  PostKind = "reshare"
	PostKindQuote    PostKind = "quote"
	PostKindReply    PostKind = "reply"
)

type ClientFamily string

const (
	ClientWeb        ClientFamily = "web"
	ClientMobile     ClientFamily = "mobile"
	ClientThirdParty ClientFamily = "third_party_api"
)

type MediaProvenance string

const (
	MediaProvC2PA MediaProvenance = "c2pa_present"
	MediaProvHash MediaProvenance = "hash_only"
	MediaProvNone MediaProvenance = "none"
)

// HexHash8 is a fixed 8-char lowercase hex string (privacy-preserving daily-salted hash).
// Use ValidateHexHash8 to check validity.
type HexHash8 string

// ProvenanceTag represents the metadata about a transparency event.
type ProvenanceTag struct {
	AcctAgeBucket  AcctAge         `json:"acct_age_bucket"`  // required
	AcctType       AcctType        `json:"acct_type"`        // required
	AutomationFlag AutomationFlag  `json:"automation_flag"`  // required
	PostKind       PostKind        `json:"post_kind"`        // required
	ClientFamily   ClientFamily    `json:"client_family"`    // required
	MediaProvenance MediaProvenance `json:"media_provenance"` // required
	DedupHash      HexHash8        `json:"dedup_hash"`       // required (8 hex chars)
	OriginHint     string          `json:"origin_hint,omitempty"` // optional ISO-3166 (e.g., "US" or "US-CA")
}
