// Code generated by Civic Transparency schema generator; DO NOT EDIT.
//
// Source-schema:   series.schema.json
// Schema-sha256:   acf1664027df36e92afba906343a652cc07c12ebeb333467bed522cfb179c3b0
// Spec-version:    0.2.1
//
// This file contains the canonical Go representation of the schema above.
// JSON struct tags match the schema field names. Enumerations are expressed
// as typed string constants. Numeric and range constraints can be checked
// with the validation helpers in validation.go.  Package-level documentation
// is in doc.go.

package types

import "regexp"

// ReHex8 matches an 8-character lowercase hex string.
var ReHex8 = regexp.MustCompile(`^[a-f0-9]{8}$`)

// ReISO3166 matches a 2-letter ISO-3166 country code with optional subdivision.
var ReISO3166 = regexp.MustCompile(`^[A-Z]{2}(-[A-Z0-9]{1,3})?$`)
